name: Keep heroku deployment alive
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  curl:
    runs-on: ubuntu-latest
    name: Keep heroku deployment alive
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: ${{ secrets.APP_URL }}
